ap_poll_url = 'https://apnews.com/hub/ap-top-25-college-football-poll'
sagarin_ratings_url = 'http://sagarin.com/sports/cfsend.htm'
espn_fpi_url = 'https://www.espn.com/college-football/fpi'
massey_ratings_url = 'https://masseyratings.com/cf/fbs/ratings'
fei_ratings_url = 'https://www.bcftoys.com/2022-fei/'

massey_ratings_data_enpoint = 'https://masseyratings.com/json/rate.php?argv=kiqB7tdov4KNhxOtPC9JHm3zh_lITb0Z-0GdxzvAPDb1wPnhbluRKzKy0hSBj-gVP3XmvNm8l6ksrUVUer342g..&task=json'

conferences = [
	['Southeastern Conference', 'SEC'],
	['Big 10 Conference', 'Big 10'],
	['Atlantic Coast Conference', 'ACC'],
	['Big 12 Conference', 'Big 12'],
	['Pacific Coast Conference', 'PAC 12'],
	['American Athletic Conference', 'AAC'],
	['Sun Belt Conference', 'Sun Belt'],
	['Mountain West Conference', 'Mountain West'],
	['Conference USA', 'Conference USA'],
	['Mid-American Conference', 'Mid-American'],
	['Independednts (FBS)', 'Independents']
]

conference_teams = {
	'SEC': ['Florida', 'Georgia', 'Kentucky', 'Missouri', 'South Carolina', 'Tennessee', 'Vanderbilt',
					'Alabama', 'Arkansas', 'Auburn', 'LSU', 'Mississippi', 'Mississippi State', 'Texas A&M'],

	'Big 10': ['Ohio State', 'Indiana', 'Penn State', 'Maryland', 'Rutgers', 'Michigan', 'Michigan State',
						'Northwestern', 'Iowa', 'Wisconsin', 'Minnesota', 'Nebraska', 'Purdue', 'Illinois'],

	'ACC': ['Clemson', 'Miami', 'North Carolina', 'NC State', 'Boston College', 'Pittsburgh', 'Virginia Tech',
					'Virginia', 'Wake Forest', 'Georgia Tech', 'Louisville', 'Florida State', 'Duke', 'Syracuse'],

	'Big 12': ['Texas', 'Oklahoma', 'Baylor', 'Iowa State', 'Oklahoma State', 'West Virginia',
		 				'Kansas State', 'Kansas', 'Texas Tech', 'TCU'],

	'PAC 12': ['Washington', 'Oregon', 'Stanford', 'Oregon State', 'Washington State', 'California',
						'USC', 'Colorado', 'Utah', 'Arizona State', 'UCLA', 'Arizona'],

	'AAC': ['Cincinnati', 'UCF', 'Memphis', 'SMU', 'Houston', 'Tulane', 'East Carolina', 'South Florida', 'Navy', 'Tulsa', 'Temple'],

	'Sun Belt': ['Appalachian State', 'Coastal Carolina', 'Georgia Southern', 'Georgia State', 'Troy', 'Marshall', 'Old Dominion',
							'Arkansas State', 'Louisiana', 'UL Monroe', 'South Alabama', 'Texas State', 'James Madison', 'Southern Miss'],

	'Mountain West': ['Air Force', 'Boise State', 'Colorado State', 'Fresno State', 'Hawaii', 'Nevada',
										'New Mexico', 'San Diego State', 'San Jose State', 'UNLV', 'Utah State', 'Wyoming'],

	'Conference USA': ['Charlotte', 'FIU', 'FAU', 'Middle Tennessee', 'Western Kentucky',
										'Louisiana Tech', 'North Texas', 'Rice', 'UAB', 'UTEP', 'UTSA'],

	'Mid-American': ['Buffalo', 'Kent State', 'Miami (OH)', 'Ohio', 'Akron', 'Bowling Green', 'Ball State',
									'Toledo', 'Western Michigan', 'Central Michigan', 'Eastern Michigan', 'Northern Illinois'],

	'Independents': ['Notre Dame', 'BYU', 'Liberty', 'Army', 'New Mexico State', 'Connecticut', 'Massachusetts']
}

team_conferences = {
	'Florida': 'SEC',
	'Georgia': 'SEC',
	'Kentucky': 'SEC',
	'Missouri': 'SEC',
	'South Carolina': 'SEC',
	'Tennessee': 'SEC',
	'Vanderbilt': 'SEC',
	'Alabama': 'SEC',
	'Arkansas': 'SEC',
	'Auburn': 'SEC',
	'LSU': 'SEC',
	'Mississippi': 'SEC',
	'Mississippi State': 'SEC',
	'Texas A&M': 'SEC',

	'Ohio State': 'Big 10',
	'Indiana': 'Big 10',
	'Penn State': 'Big 10',
	'Maryland': 'Big 10',
	'Rutgers': 'Big 10',
	'Michigan': 'Big 10',
	'Michigan State': 'Big 10',
	'Northwestern': 'Big 10',
	'Iowa': 'Big 10',
	'Wisconsin': 'Big 10',
	'Minnesota': 'Big 10',
	'Nebraska': 'Big 10',
	'Purdue': 'Big 10',
	'Illinois': 'Big 10',
	
	'Clemson': 'ACC',
	'Miami': 'ACC',
	'North Carolina': 'ACC',
	'NC State': 'ACC',
	'Boston College': 'ACC',
	'Pittsburgh': 'ACC',
	'Virginia Tech': 'ACC',
	'Virginia': 'ACC',
	'Wake Forest': 'ACC',
	'Georgia Tech': 'ACC',
	'Louisville': 'ACC',
	'Florida State': 'ACC',
	'Duke': 'ACC',
	'Syracuse': 'ACC',
	
	'Texas': 'Big 12',
	'Oklahoma': 'Big 12',
	'Baylor': 'Big 12',
	'Iowa State': 'Big 12',
	'Oklahoma State': 'Big 12',
	'West Virginia': 'Big 12',
	'Kansas State': 'Big 12',
	'Kansas': 'Big 12',
	'Texas Tech': 'Big 12',
	'TCU': 'Big 12',
	
	'Washington': 'PAC 12',
	'Oregon': 'PAC 12',
	'Stanford': 'PAC 12',
	'Oregon State': 'PAC 12',
	'Washington State': 'PAC 12',
	'California': 'PAC 12',
	'USC': 'PAC 12',
	'Colorado': 'PAC 12',
	'Utah': 'PAC 12',
	'Arizona State': 'PAC 12',
	'UCLA': 'PAC 12',
	'Arizona': 'PAC 12',
	
	'Cincinnati': 'AAC',
	'UCF': 'AAC',
	'Memphis': 'AAC',
	'SMU': 'AAC',
	'Houston': 'AAC',
	'Tulane': 'AAC',
	'East Carolina': 'AAC',
	'South Florida': 'AAC',
	'Navy': 'AAC',
	'Tulsa': 'AAC',
	'Temple': 'AAC',
	
	'Appalachian State': 'Sun Belt',
	'Coastal Carolina': 'Sun Belt',
	'Georgia Southern': 'Sun Belt',
	'Georgia State': 'Sun Belt',
	'Troy': 'Sun Belt',
	'Marshall': 'Sun Belt',
	'Old Dominion': 'Sun Belt',
	'Arkansas State': 'Sun Belt',
	'Louisiana': 'Sun Belt',
	'UL Monroe': 'Sun Belt',
	'South Alabama': 'Sun Belt',
	'Texas State': 'Sun Belt',
	'James Madison': 'Sun Belt',
	'Southern Miss': 'Sun Belt',
	
	'Air Force': 'Mountain West',
	'Boise State': 'Mountain West',
	'Colorado State': 'Mountain West',
	'Fresno State': 'Mountain West',
	'Hawaii': 'Mountain West',
	'Nevada': 'Mountain West',
	'New Mexico': 'Mountain West',
	'San Diego State': 'Mountain West',
	'San Jose State': 'Mountain West',
	'UNLV': 'Mountain West',
	'Utah State': 'Mountain West',
	'Wyoming': 'Mountain West',
	
	'Charlotte': 'Conference USA',
	'FIU': 'Conference USA',
	'FAU': 'Conference USA',
	'Middle Tennessee': 'Conference USA',
	'Western Kentucky': 'Conference USA',
	'Louisiana Tech': 'Conference USA',
	'North Texas': 'Conference USA',
	'Rice': 'Conference USA',
	'UAB': 'Conference USA',
	'UTEP': 'Conference USA',
	'UTSA': 'Conference USA',
	
	'Buffalo': 'Mid-American',
	'Kent State': 'Mid-American',
	'Miami (OH)': 'Mid-American',
	'Ohio': 'Mid-American',
	'Akron': 'Mid-American',
	'Bowling Green': 'Mid-American',
	'Ball State': 'Mid-American',
	'Toledo': 'Mid-American',
	'Western Michigan': 'Mid-American',
	'Central Michigan': 'Mid-American',
	'Eastern Michigan': 'Mid-American',
	'Northern Illinois': 'Mid-American',

	'Notre Dame': 'Independents',
	'BYU': 'Independents',
	'Liberty': 'Independents',
	'Army': 'Independents',
	'New Mexico State': 'Independents',
	'Connecticut': 'Independents',
	'Massachusetts': 'Independents',
}

ap_poll_team_name_replacements = [
	[
		'North Carolina State',
		'Ole Miss',
	],
	[
		'NC State',
		'Mississippi',
	]
]

sagarin_ratings_team_name_replacements = [
	[
		'Southern California',
		'Miami-Florida',
		'Central Florida(UCF)',
		'Miami-Ohio',
		'Army West Point',
		'Florida Atlantic',
		'Hawai\'i',
		'LouisianaMonroe(ULM)',
		'Fla. International'
	],
	[
		'USC',
		'Miami',
		'UCF',
		'Miami (OH)',
		'Army',
		'FAU',
		'Hawaii',
		'UL Monroe',
		'FIU'
	]
]

espn_fpi_team_name_replacements = [
	[
		'Ole Miss',
		'Hawai\'i',
		'Florida Atlantic',
		'Florida International',
		'San José State',
		'UConn',
		'UMass',
	],
	[
		'Mississippi',
		'Hawaii',
		'FAU',
		'FIU',
		'San Jose State',
		'Connecticut',
		'Massachusetts',
	]
]

espn_fpi_double_mascot_names = [
	'Crimson Tide',
	'Golden Gophers',
	'Horned Frogs',
	'Thundering Herd',
	'Black Knights',
	'Eagles',
	'Green Wave',
	'Golden Bears',
	'Ragin\' Cajuns',
	'Fighting Illini',
	'Scarlet Knights',
	'Golden Hurricane',
	'Wolf Pack',
	'Blue Devils',
	'Rainbow Warriors',
]

massey_ratings_team_name_replacements = [
	[
		'Miami FL',
		'WKU',
		'Coastal Car',
		'W Michigan',
		'C Michigan',
		'Ga Southern',
		'Miami OH',
		'FL Atlantic',
		'N Illinois',
		'E Michigan',
		'UT San Antonio',
		'MTSU',
		'Kent',
		'ULM',
		'Florida Intl'
	],
	[
		'Miami',
		'Western Kentucky',
		'Coastal Carolina',
		'Western Michigan',
		'Central Michigan',
		'Georgia Southern',
		'Miami (OH)',
		'FAU',
		'Northern Illinois',
		'Eastern Michigan',
		'UTSA',
		'Middle Tennessee',
		'Kent State',
		'UL Monroe',
		'FIU'
	]
]

fei_ratings_team_name_replacements = [
	[
		'Ole Miss',
		'Florida Atlantic',
		'Southern Mississippi',
		'Florida International'
	],
	[
		'Mississippi',
		'FAU',
		'Southern Miss',
		'FIU'
	]
]

cbs_shortname_lookup = {
	'Alabama': 'BAMA',
	'Arkansas': 'ARK',
	'Auburn': 'AUBURN',
	'Florida': 'FLA',
	'Georgia': 'UGA',
	'Kentucky': 'UK',
	'LSU': 'LSU',
	'Miss. State': 'MISSST',
	'Missouri': 'MIZZOU',
	'Ole Miss': 'MISS',
	'South Carolina': 'SC',
	'Tennessee': 'TENN',
	'Texas A&M': 'TXAM',
	'Vanderbilt': 'VANDY',
	'Illinois': 'ILL',
	'Indiana': 'IND',
	'Iowa': 'IOWA',
	'Maryland': 'MD',
	'Michigan': 'MICH',
	'Michigan St.': 'MICHST',
	'Minnesota': 'MINN',
	'Nebraska': 'NEB',
	'Northwestern': 'NWEST',
	'Ohio St.': 'OHIOST',
	'Penn St.': 'PSU',
	'Purdue': 'PURDUE',
	'Rutgers': 'RUT',
	'Wisconsin': 'WISC',
	'Boston College': 'BC',
	'Clemson': 'CLEM',
	'Duke': 'DUKE',
	'Florida State': 'FSU',
	'Georgia Tech': 'GATECH',
	'Louisville': 'LVILLE',
	'Miami (Fla.)': 'MIAMI',
	'NC State': 'NCST',
	'North Carolina': 'UNC',
	'Pittsburgh': 'PITT',
	'Syracuse': 'CUSE',
	'Virginia': 'UVA',
	'Virginia Tech': 'VATECH',
	'Wake Forest': 'WAKE',
	'Baylor': 'BAYLOR',
	'Iowa St.': 'IOWAST',
	'Kansas': 'KANSAS',
	'Kansas St.': 'KSTATE',
	'Oklahoma': 'OKLA',
	'Okla. St.': 'OKLAST',
	'TCU': 'TCU',
	'Texas': 'TEXAS',
	'Texas Tech': 'TXTECH',
	'West Virginia': 'WVU',
	'Arizona': 'ARIZ',
	'Arizona St.': 'ARIZST',
	'California': 'CAL',
	'Colorado': 'COLO',
	'Oregon': 'OREG',
	'Oregon St.': 'OREGST',
	'Stanford': 'STNFRD',
	'UCLA': 'UCLA',
	'USC': 'USC',
	'Utah': 'UTAH',
	'Washington': 'WASH',
	'Washington St.': 'WASHST',
	'Cincinnati': 'CINCY',
	'East Carolina': 'ECU',
	'Houston': 'HOU',
	'Memphis': 'MEMP',
	'Navy': 'NAVY',
	'SMU': 'SMU',
	'South Florida': 'SFLA',
	'Temple': 'TEMPLE',
	'Tulane': 'TULANE',
	'Tulsa': 'TULSA',
	'UCF': 'UCF',
	'App. St.': 'APLST',
	'Arkansas St.': 'ARKST',
	'C. Carolina': 'CSTCAR',
	'Ga. Southern': 'GAS',
	'Georgia St.': 'GAST',
	'James Madison': 'JMAD',
	
	# 'Louisiana': 'LALAF',
	'Louisiana': 'UL',

	'Marshall': 'MRSHL',
	'Old Dominion': 'ODU',
	'South Alabama': 'SALA',
	'So. Miss': 'USM',
	'Texas St.': 'TXSTSM',
	'Troy': 'TROY',
	'UL-Monroe': 'LAMON',
	'Air Force': 'AF',
	'Boise St.': 'BOISE',
	'Colorado St.': 'COLOST',
	'Fresno St.': 'FRESNO',
	'Hawaii': 'HAWAII',
	'Nevada': 'NEVADA',
	'New Mexico': 'NMEX',
	'San Diego St.': 'SDGST',
	'San Jose St.': 'SJST',
	'UNLV': 'UNLV',
	'Utah St.': 'UTAHST',
	'Wyoming': 'WYO',
	'Akron': 'AKRON',
	'Ball St.': 'BALLST',
	'Bowling Green': 'BGREEN',
	'Buffalo': 'BUFF',
	'C. Michigan': 'CMICH',
	'E. Michigan': 'EMICH',
	'Kent St.': 'KENTST',
	'Miami (Ohio)': 'MIAOH',
	'N. Illinois': 'NILL',
	'Ohio': 'OHIO',
	'Toledo': 'TOLEDO',
	'W. Michigan': 'WMICH',
	'Charlotte': 'CHARLO',
	'FIU': 'FIU',
	'FAU': 'FAU',
	'Louisiana Tech': 'LATECH',
	'Middle Tenn.': 'MTSU',
	'North Texas': 'NTEXAS',
	'Rice': 'RICE',
	'UAB': 'UAB',
	'UTEP': 'UTEP',
	'UTSA': 'TXSA',
	'W. Kentucky': 'WKY',
	'Army': 'ARMY',
	'BYU': 'BYU',
	'Liberty': 'LIB',
	'New Mexico St.': 'NMEXST',
	'Notre Dame': 'ND',
	'UConn': 'UCONN',
	'UMass': 'UMASS'
}

official_name_lookup = {
	'BAMA': 'Alabama',
	'ARK': 'Arkansas',
	'AUBURN': 'Auburn',
	'FLA': 'Florida',
	'UGA': 'Georgia',
	'UK': 'Kentucky',
	'LSU': 'LSU',
	'MISSST': 'Mississippi State',
	'MIZZOU': 'Missouri',
	'MISS': 'Mississippi',
	'SC': 'South Carolina',
	'TENN': 'Tennessee',
	'TXAM': 'Texas A&M',
	'VANDY': 'Vanderbilt',
	'ILL': 'Illinois',
	'IND': 'Indiana',
	'IOWA': 'Iowa',
	'MD': 'Maryland',
	'MICH': 'Michigan',
	'MICHST': 'Michigan State',
	'MINN': 'Minnesota',
	'NEB': 'Nebraska',
	'NWEST': 'Northwestern',
	'OHIOST': 'Ohio State',
	'PSU': 'Penn State',
	'PURDUE': 'Purdue',
	'RUT': 'Rutgers',
	'WISC': 'Wisconsin',
	'BC': 'Boston College',
	'CLEM': 'Clemson',
	'DUKE': 'Duke',
	'FSU': 'Florida State',
	'GATECH': 'Georgia Tech',
	'LVILLE': 'Louisville',
	'MIAMI': 'Miami',
	'NCST': 'NC State',
	'UNC': 'North Carolina',
	'PITT': 'Pittsburgh',
	'CUSE': 'Syracuse',
	'UVA': 'Virginia',
	'VATECH': 'Virginia Tech',
	'WAKE': 'Wake Forest',
	'BAYLOR': 'Baylor',
	'IOWAST': 'Iowa State',
	'KANSAS': 'Kansas',
	'KSTATE': 'Kansas State',
	'OKLA': 'Oklahoma',
	'OKLAST': 'Oklahoma State',
	'TCU': 'TCU',
	'TEXAS': 'Texas',
	'TXTECH': 'Texas Tech',
	'WVU': 'West Virginia',
	'ARIZ': 'Arizona',
	'ARIZST': 'Arizona State',
	'CAL': 'California',
	'COLO': 'Colorado',
	'OREG': 'Oregon',
	'OREGST': 'Oregon State',
	'STNFRD': 'Stanford',
	'UCLA': 'UCLA',
	'USC': 'USC',
	'UTAH': 'Utah',
	'WASH': 'Washington',
	'WASHST': 'Washington State',
	'CINCY': 'Cincinnati',
	'ECU': 'East Carolina',
	'HOU': 'Houston',
	'MEMP': 'Memphis',
	'NAVY': 'Navy',
	'SMU': 'SMU',
	'SFLA': 'South Florida',
	'TEMPLE': 'Temple',
	'TULANE': 'Tulane',
	'TULSA': 'Tulsa',
	'UCF': 'UCF',
	'APLST': 'Appalachian State',
	'ARKST': 'Arkansas State',
	'CSTCAR': 'Coastal Carolina',
	'GAS': 'Georgia Southern',
	'GAST': 'Georgia State',
	'JMAD': 'James Madison',

	'LALAF': 'Louisiana',
	'UL': 'Louisiana',

	'MRSHL': 'Marshall',
	'ODU': 'Old Dominion',
	'SALA': 'South Alabama',
	'USM': 'Southern Miss',
	'TXSTSM': 'Texas State',
	'TROY': 'Troy',
	'LAMON': 'UL Monroe',
	'AF': 'Air Force',
	'BOISE': 'Boise State',
	'COLOST': 'Colorado State',
	'FRESNO': 'Fresno State',
	'HAWAII': 'Hawaii',
	'NEVADA': 'Nevada',
	'NMEX': 'New Mexico',
	'SDGST': 'San Diego State',
	'SJST': 'San Jose State',
	'UNLV': 'UNLV',
	'UTAHST': 'Utah State',
	'WYO': 'Wyoming',
	'AKRON': 'Akron',
	'BALLST': 'Ball State',
	'BGREEN': 'Bowling Green',
	'BUFF': 'Buffalo',
	'CMICH': 'Central Michigan',
	'EMICH': 'Eastern Michigan',
	'KENTST': 'Kent State',
	'MIAOH': 'Miami (OH)',
	'NILL': 'Northern Illinois',
	'OHIO': 'Ohio',
	'TOLEDO': 'Toledo',
	'WMICH': 'Western Michigan',
	'CHARLO': 'Charlotte',
	'FIU': 'FIU',
	'FAU': 'FAU',
	'LATECH': 'Louisiana Tech',
	'MTSU': 'Middle Tennessee',
	'NTEXAS': 'North Texas',
	'RICE': 'Rice',
	'UAB': 'UAB',
	'UTEP': 'UTEP',
	'TXSA': 'UTSA',
	'WKY': 'Western Kentucky',
	'ARMY': 'Army',
	'BYU': 'BYU',
	'LIB': 'Liberty',
	'NMEXST': 'New Mexico State',
	'ND': 'Notre Dame',
	'UCONN': 'Connecticut',
	'UMASS': 'Massachusetts'
}

cbs_statistics_rename = {
	'1st Downs': 'first_downs',
	'Rushing': 'first_down_rushing_attempts',
	'Passing': 'first_down_passing_attempts',
	'Penalty': 'first_down_penalties',
	'3rd Down Conv': 'third_down_conversion',
	'4th Down Conv': 'fourth_down_conversion',
	'Total Net Yards': 'total_net_yards',
	'Total Plays': 'total_plays',
	'Avg Gain': 'average_yards_per_play',
	'Net Yards Rushing': 'net_yards_rushing',
	'Rush Attempts': 'rushing_attempts',
	'Avg Rush Yards': 'average_rushing_yards_per_rushing_attempt',
	'Yards Passing': 'total_yards_passing',
	'Comp. - Att.': 'pass_completions-pass_attempts',
	'Yards Per Pass': 'adjusted_yards_per_pass_attempt',
	'Penalties - Yards': 'penalties-penalty_yards',
	'Touchdowns': 'touchdowns',
	'Rushing TDs': 'rushing_touchdowns',
	'Passing TDs': 'passing_touchdowns',
	'Other': 'other_touchdowns',
	'Turnovers': 'turnovers',
	'Fumbles - Lost': 'fumbles-fumbles_lost',
	'Int. Thrown': 'interceptions_thrown',
	'Punts - Avg': 'punts-average_punt_yards',
	'Return Yards': 'total_return_yards',
	'Punts - Returns': 'punts_returns-punt_return_yards',
	'Kickoffs - Returns': 'kickoffs_returns-kickoff_return_yards',
	'Int. - Returns': 'interceptions_returns-interception_return_yards',
	'Safeties': 'safeties',
}