shortname_lookup = {
	'Alabama': 'BAMA',
	'Arkansas': 'ARK',
	'Auburn': 'AUBURN',
	'Florida': 'FLA',
	'Georgia': 'UGA',
	'Kentucky': 'UK',
	'LSU': 'LSU',
	'Miss. State': 'MISSST',
	'Missouri': 'MIZZOU',
	'Ole Miss': 'MISS',
	'South Carolina': 'SC',
	'Tennessee': 'TENN',
	'Texas A&M': 'TXAM',
	'Vanderbilt': 'VANDY',

	'Illinois': 'ILL',
	'Indiana': 'IND',
	'Iowa': 'IOWA',
	'Maryland': 'MD',
	'Michigan': 'MICH',
	'Michigan St.': 'MICHST',
	'Minnesota': 'MINN',
	'Nebraska': 'NEB',
	'Northwestern': 'NWEST',
	'Ohio St.': 'OHIOST',
	'Penn St.': 'PSU',
	'Purdue': 'PURDUE',
	'Rutgers': 'RUT',
	'Wisconsin': 'WISC',

	'Boston College': 'BC',
	'Clemson': 'CLEM',
	'Duke': 'DUKE',
	'Florida State': 'FSU',
	'Georgia Tech': 'GATECH',
	'Louisville': 'LVILLE',
	'Miami (Fla.)': 'MIAMI',
	'NC State': 'NCST',
	'North Carolina': 'UNC',
	'Pittsburgh': 'PITT',
	'Syracuse': 'CUSE',
	'Virginia': 'UVA',
	'Virginia Tech': 'VATECH',
	'Wake Forest': 'WAKE',

	'Baylor': 'BAYLOR',
	'Iowa St.': 'IOWAST',
	'Kansas': 'KANSAS',
	'Kansas St.': 'KSTATE',
	'Oklahoma': 'OKLA',
	'Okla. St.': 'OKLAST',
	'TCU': 'TCU',
	'Texas': 'TEXAS',
	'Texas Tech': 'TXTECH',
	'West Virginia': 'WVU',

	'Arizona': 'ARIZ',
	'Arizona St.': 'ARIZST',
	'California': 'CAL',
	'Colorado': 'COLO',
	'Oregon': 'OREG',
	'Oregon St.': 'OREGST',
	'Stanford': 'STNFRD',
	'UCLA': 'UCLA',
	'USC': 'USC',
	'Utah': 'UTAH',
	'Washington': 'WASH',
	'Washington St.': 'WASHST',

	'Cincinnati': 'CINCY',
	'East Carolina': 'ECU',
	'Houston': 'HOU',
	'Memphis': 'MEMP',
	'Navy': 'NAVY',
	'SMU': 'SMU',
	'South Florida': 'SFLA',
	'Temple': 'TEMPLE',
	'Tulane': 'TULANE',
	'Tulsa': 'TULSA',
	'UCF': 'UCF',

	'App. St.': 'APLST',
	'Arkansas St.': 'ARKST',
	'C. Carolina': 'CSTCAR',
	'Ga. Southern': 'GAS',
	'Georgia St.': 'GAST',
	'James Madison': 'JMAD',
	
	# 'Louisiana': 'LALAF',
	'Louisiana': 'UL',

	'Marshall': 'MRSHL',
	'Old Dominion': 'ODU',
	'South Alabama': 'SALA',
	'So. Miss': 'USM',
	'Texas St.': 'TXSTSM',
	'Troy': 'TROY',
	'UL-Monroe': 'LAMON',
	'Air Force': 'AF',
	'Boise St.': 'BOISE',
	'Colorado St.': 'COLOST',
	'Fresno St.': 'FRESNO',
	'Hawaii': 'HAWAII',
	'Nevada': 'NEVADA',
	'New Mexico': 'NMEX',
	'San Diego St.': 'SDGST',
	'San Jose St.': 'SJST',
	'UNLV': 'UNLV',
	'Utah St.': 'UTAHST',
	'Wyoming': 'WYO',
	'Akron': 'AKRON',
	'Ball St.': 'BALLST',
	'Bowling Green': 'BGREEN',
	'Buffalo': 'BUFF',
	'C. Michigan': 'CMICH',
	'E. Michigan': 'EMICH',
	'Kent St.': 'KENTST',
	'Miami (Ohio)': 'MIAOH',
	'N. Illinois': 'NILL',
	'Ohio': 'OHIO',
	'Toledo': 'TOLEDO',
	'W. Michigan': 'WMICH',
	'Charlotte': 'CHARLO',
	'FIU': 'FIU',
	'FAU': 'FAU',
	'Louisiana Tech': 'LATECH',
	'Middle Tenn.': 'MTSU',
	'North Texas': 'NTEXAS',
	'Rice': 'RICE',
	'UAB': 'UAB',
	'UTEP': 'UTEP',
	'UTSA': 'TXSA',
	'W. Kentucky': 'WKY',
	
	'Army': 'ARMY',
	'BYU': 'BYU',
	'Liberty': 'LIB',
	'New Mexico St.': 'NMEXST',
	'Notre Dame': 'ND',
	'UConn': 'UCONN',
	'UMass': 'UMASS'
}

official_name_lookup = {
	'BAMA': 'Alabama',
	'ARK': 'Arkansas',
	'AUBURN': 'Auburn',
	'FLA': 'Florida',
	'UGA': 'Georgia',
	'UK': 'Kentucky',
	'LSU': 'LSU',
	'MISSST': 'Mississippi State',
	'MIZZOU': 'Missouri',
	'MISS': 'Mississippi',
	'SC': 'South Carolina',
	'TENN': 'Tennessee',
	'TXAM': 'Texas A&M',
	'VANDY': 'Vanderbilt',
	'ILL': 'Illinois',
	'IND': 'Indiana',
	'IOWA': 'Iowa',
	'MD': 'Maryland',
	'MICH': 'Michigan',
	'MICHST': 'Michigan State',
	'MINN': 'Minnesota',
	'NEB': 'Nebraska',
	'NWEST': 'Northwestern',
	'OHIOST': 'Ohio State',
	'PSU': 'Penn State',
	'PURDUE': 'Purdue',
	'RUT': 'Rutgers',
	'WISC': 'Wisconsin',
	'BC': 'Boston College',
	'CLEM': 'Clemson',
	'DUKE': 'Duke',
	'FSU': 'Florida State',
	'GATECH': 'Georgia Tech',
	'LVILLE': 'Louisville',
	'MIAMI': 'Miami',
	'NCST': 'NC State',
	'UNC': 'North Carolina',
	'PITT': 'Pittsburgh',
	'CUSE': 'Syracuse',
	'UVA': 'Virginia',
	'VATECH': 'Virginia Tech',
	'WAKE': 'Wake Forest',
	'BAYLOR': 'Baylor',
	'IOWAST': 'Iowa State',
	'KANSAS': 'Kansas',
	'KSTATE': 'Kansas State',
	'OKLA': 'Oklahoma',
	'OKLAST': 'Oklahoma State',
	'TCU': 'TCU',
	'TEXAS': 'Texas',
	'TXTECH': 'Texas Tech',
	'WVU': 'West Virginia',
	'ARIZ': 'Arizona',
	'ARIZST': 'Arizona State',
	'CAL': 'California',
	'COLO': 'Colorado',
	'OREG': 'Oregon',
	'OREGST': 'Oregon State',
	'STNFRD': 'Stanford',
	'UCLA': 'UCLA',
	'USC': 'USC',
	'UTAH': 'Utah',
	'WASH': 'Washington',
	'WASHST': 'Washington State',
	'CINCY': 'Cincinnati',
	'ECU': 'East Carolina',
	'HOU': 'Houston',
	'MEMP': 'Memphis',
	'NAVY': 'Navy',
	'SMU': 'SMU',
	'SFLA': 'South Florida',
	'TEMPLE': 'Temple',
	'TULANE': 'Tulane',
	'TULSA': 'Tulsa',
	'UCF': 'UCF',
	'APLST': 'Appalachian State',
	'ARKST': 'Arkansas State',
	'CSTCAR': 'Coastal Carolina',
	'GAS': 'Georgia Southern',
	'GAST': 'Georgia State',
	'JMAD': 'James Madison',

	'LALAF': 'Louisiana',
	'UL': 'Louisiana',

	'MRSHL': 'Marshall',
	'ODU': 'Old Dominion',
	'SALA': 'South Alabama',
	'USM': 'Southern Miss',
	'TXSTSM': 'Texas State',
	'TROY': 'Troy',
	'LAMON': 'UL Monroe',
	'AF': 'Air Force',
	'BOISE': 'Boise State',
	'COLOST': 'Colorado State',
	'FRESNO': 'Fresno State',
	'HAWAII': 'Hawaii',
	'NEVADA': 'Nevada',
	'NMEX': 'New Mexico',
	'SDGST': 'San Diego State',
	'SJST': 'San Jose State',
	'UNLV': 'UNLV',
	'UTAHST': 'Utah State',
	'WYO': 'Wyoming',
	'AKRON': 'Akron',
	'BALLST': 'Ball State',
	'BGREEN': 'Bowling Green',
	'BUFF': 'Buffalo',
	'CMICH': 'Central Michigan',
	'EMICH': 'Eastern Michigan',
	'KENTST': 'Kent State',
	'MIAOH': 'Miami (OH)',
	'NILL': 'Northern Illinois',
	'OHIO': 'Ohio',
	'TOLEDO': 'Toledo',
	'WMICH': 'Western Michigan',
	'CHARLO': 'Charlotte',
	'FIU': 'FIU',
	'FAU': 'FAU',
	'LATECH': 'Louisiana Tech',
	'MTSU': 'Middle Tennessee',
	'NTEXAS': 'North Texas',
	'RICE': 'Rice',
	'UAB': 'UAB',
	'UTEP': 'UTEP',
	'TXSA': 'UTSA',
	'WKY': 'Western Kentucky',
	'ARMY': 'Army',
	'BYU': 'BYU',
	'LIB': 'Liberty',
	'NMEXST': 'New Mexico State',
	'ND': 'Notre Dame',
	'UCONN': 'Connecticut',
	'UMASS': 'Massachusetts'
}

statistics_rename = {
	'1st Downs': 'first_downs',
	'Rushing': 'first_down_rushing_attempts',
	'Passing': 'first_down_passing_attempts',
	'Penalty': 'first_down_penalties',
	'3rd Down Conv': 'third_down_conversion',
	'4th Down Conv': 'fourth_down_conversion',
	'Total Net Yards': 'total_net_yards',
	'Total Plays': 'total_plays',
	'Avg Gain': 'average_yards_per_play',
	'Net Yards Rushing': 'net_yards_rushing',
	'Rush Attempts': 'rushing_attempts',
	'Avg Rush Yards': 'average_rushing_yards_per_rushing_attempt',
	'Yards Passing': 'total_yards_passing',
	'Comp. - Att.': 'pass_completions-pass_attempts',
	'Yards Per Pass': 'adjusted_yards_per_pass_attempt',
	'Penalties - Yards': 'penalties-penalty_yards',
	'Touchdowns': 'touchdowns',
	'Rushing TDs': 'rushing_touchdowns',
	'Passing TDs': 'passing_touchdowns',
	'Other': 'other_touchdowns',
	'Turnovers': 'turnovers',
	'Fumbles - Lost': 'fumbles-fumbles_lost',
	'Int. Thrown': 'interceptions_thrown',
	'Punts - Avg': 'punts-average_punt_yards',
	'Return Yards': 'total_return_yards',
	'Punts - Returns': 'punts_returns-punt_return_yards',
	'Kickoffs - Returns': 'kickoffs_returns-kickoff_return_yards',
	'Int. - Returns': 'interceptions_returns-interception_return_yards',
	'Safeties': 'safeties',
}

official_name_replacement = {
	'Louisiana State': 'LSU',
	'Miami (FL)': 'Miami',
	'North Carolina State': 'NC State',
	'Texas Christian': 'TCU',
	'Southern California': 'USC',
	'Southern Methodist': 'SMU',
	'Central Florida': 'UCF',
	'Southern Mississippi': 'Southern Miss',
	'Middle Tennessee State': 'Middle Tennessee',
	'Louisiana-Monroe': 'UL Monroe',
	'Nevada-Las Vegas': 'UNLV',
	'Florida International': 'FIU',
	'Florida Atlantic': 'FAU',
	'Alabama-Birmingham': 'UAB',
	'Texas-El Paso': 'UTEP',
	'Texas-San Antonio': 'UTSA',
	'Brigham Young': 'BYU',
}