conferences = [
	['Southeastern Conference', 'SEC'],
	['Big 10 Conference', 'Big 10'],
	['Atlantic Coast Conference', 'ACC'],
	['Big 12 Conference', 'Big 12'],
	['Pacific Coast Conference', 'PAC 12'],
	['American Athletic Conference', 'AAC'],
	['Sun Belt Conference', 'Sun Belt'],
	['Mountain West Conference', 'Mountain West'],
	['Conference USA', 'Conference USA'],
	['Mid-American Conference', 'Mid-American'],
	['Independednts (FBS)', 'Independents']
]

conference_teams = {
	'SEC': ['Florida', 'Georgia', 'Kentucky', 'Missouri', 'South Carolina', 'Tennessee', 'Vanderbilt',
					'Alabama', 'Arkansas', 'Auburn', 'LSU', 'Mississippi', 'Mississippi State', 'Texas A&M'],

	'Big 10': ['Ohio State', 'Indiana', 'Penn State', 'Maryland', 'Rutgers', 'Michigan', 'Michigan State',
						'Northwestern', 'Iowa', 'Wisconsin', 'Minnesota', 'Nebraska', 'Purdue', 'Illinois'],

	'ACC': ['Clemson', 'Miami', 'North Carolina', 'NC State', 'Boston College', 'Pittsburgh', 'Virginia Tech',
					'Virginia', 'Wake Forest', 'Georgia Tech', 'Louisville', 'Florida State', 'Duke', 'Syracuse'],

	'Big 12': ['Texas', 'Oklahoma', 'Baylor', 'Iowa State', 'Oklahoma State', 'West Virginia',
		 				'Kansas State', 'Kansas', 'Texas Tech', 'TCU'],

	'PAC 12': ['Washington', 'Oregon', 'Stanford', 'Oregon State', 'Washington State', 'California',
						'USC', 'Colorado', 'Utah', 'Arizona State', 'UCLA', 'Arizona'],

	'AAC': ['Cincinnati', 'UCF', 'Memphis', 'SMU', 'Houston', 'Tulane', 'East Carolina', 'South Florida', 'Navy', 'Tulsa', 'Temple'],

	'Sun Belt': ['Appalachian State', 'Coastal Carolina', 'Georgia Southern', 'Georgia State', 'Troy', 'Marshall', 'Old Dominion',
							'Arkansas State', 'Louisiana', 'UL Monroe', 'South Alabama', 'Texas State', 'James Madison', 'Southern Miss'],

	'Mountain West': ['Air Force', 'Boise State', 'Colorado State', 'Fresno State', 'Hawaii', 'Nevada',
										'New Mexico', 'San Diego State', 'San Jose State', 'UNLV', 'Utah State', 'Wyoming'],

	'Conference USA': ['Charlotte', 'FIU', 'FAU', 'Middle Tennessee', 'Western Kentucky',
										'Louisiana Tech', 'North Texas', 'Rice', 'UAB', 'UTEP', 'UTSA'],

	'Mid-American': ['Buffalo', 'Kent State', 'Miami (OH)', 'Ohio', 'Akron', 'Bowling Green', 'Ball State',
									'Toledo', 'Western Michigan', 'Central Michigan', 'Eastern Michigan', 'Northern Illinois'],

	'Independents': ['Notre Dame', 'BYU', 'Liberty', 'Army', 'New Mexico State', 'Connecticut', 'Massachusetts']
}

team_conferences = {
	'Florida': 'SEC',
	'Georgia': 'SEC',
	'Kentucky': 'SEC',
	'Missouri': 'SEC',
	'South Carolina': 'SEC',
	'Tennessee': 'SEC',
	'Vanderbilt': 'SEC',
	'Alabama': 'SEC',
	'Arkansas': 'SEC',
	'Auburn': 'SEC',
	'LSU': 'SEC',
	'Mississippi': 'SEC',
	'Mississippi State': 'SEC',
	'Texas A&M': 'SEC',

	'Ohio State': 'Big 10',
	'Indiana': 'Big 10',
	'Penn State': 'Big 10',
	'Maryland': 'Big 10',
	'Rutgers': 'Big 10',
	'Michigan': 'Big 10',
	'Michigan State': 'Big 10',
	'Northwestern': 'Big 10',
	'Iowa': 'Big 10',
	'Wisconsin': 'Big 10',
	'Minnesota': 'Big 10',
	'Nebraska': 'Big 10',
	'Purdue': 'Big 10',
	'Illinois': 'Big 10',
	
	'Clemson': 'ACC',
	'Miami': 'ACC',
	'North Carolina': 'ACC',
	'NC State': 'ACC',
	'Boston College': 'ACC',
	'Pittsburgh': 'ACC',
	'Virginia Tech': 'ACC',
	'Virginia': 'ACC',
	'Wake Forest': 'ACC',
	'Georgia Tech': 'ACC',
	'Louisville': 'ACC',
	'Florida State': 'ACC',
	'Duke': 'ACC',
	'Syracuse': 'ACC',
	
	'Texas': 'Big 12',
	'Oklahoma': 'Big 12',
	'Baylor': 'Big 12',
	'Iowa State': 'Big 12',
	'Oklahoma State': 'Big 12',
	'West Virginia': 'Big 12',
	'Kansas State': 'Big 12',
	'Kansas': 'Big 12',
	'Texas Tech': 'Big 12',
	'TCU': 'Big 12',
	
	'Washington': 'PAC 12',
	'Oregon': 'PAC 12',
	'Stanford': 'PAC 12',
	'Oregon State': 'PAC 12',
	'Washington State': 'PAC 12',
	'California': 'PAC 12',
	'USC': 'PAC 12',
	'Colorado': 'PAC 12',
	'Utah': 'PAC 12',
	'Arizona State': 'PAC 12',
	'UCLA': 'PAC 12',
	'Arizona': 'PAC 12',
	
	'Cincinnati': 'AAC',
	'UCF': 'AAC',
	'Memphis': 'AAC',
	'SMU': 'AAC',
	'Houston': 'AAC',
	'Tulane': 'AAC',
	'East Carolina': 'AAC',
	'South Florida': 'AAC',
	'Navy': 'AAC',
	'Tulsa': 'AAC',
	'Temple': 'AAC',
	
	'Appalachian State': 'Sun Belt',
	'Coastal Carolina': 'Sun Belt',
	'Georgia Southern': 'Sun Belt',
	'Georgia State': 'Sun Belt',
	'Troy': 'Sun Belt',
	'Marshall': 'Sun Belt',
	'Old Dominion': 'Sun Belt',
	'Arkansas State': 'Sun Belt',
	'Louisiana': 'Sun Belt',
	'UL Monroe': 'Sun Belt',
	'South Alabama': 'Sun Belt',
	'Texas State': 'Sun Belt',
	'James Madison': 'Sun Belt',
	'Southern Miss': 'Sun Belt',
	
	'Air Force': 'Mountain West',
	'Boise State': 'Mountain West',
	'Colorado State': 'Mountain West',
	'Fresno State': 'Mountain West',
	'Hawaii': 'Mountain West',
	'Nevada': 'Mountain West',
	'New Mexico': 'Mountain West',
	'San Diego State': 'Mountain West',
	'San Jose State': 'Mountain West',
	'UNLV': 'Mountain West',
	'Utah State': 'Mountain West',
	'Wyoming': 'Mountain West',
	
	'Charlotte': 'Conference USA',
	'FIU': 'Conference USA',
	'FAU': 'Conference USA',
	'Middle Tennessee': 'Conference USA',
	'Western Kentucky': 'Conference USA',
	'Louisiana Tech': 'Conference USA',
	'North Texas': 'Conference USA',
	'Rice': 'Conference USA',
	'UAB': 'Conference USA',
	'UTEP': 'Conference USA',
	'UTSA': 'Conference USA',
	
	'Buffalo': 'Mid-American',
	'Kent State': 'Mid-American',
	'Miami (OH)': 'Mid-American',
	'Ohio': 'Mid-American',
	'Akron': 'Mid-American',
	'Bowling Green': 'Mid-American',
	'Ball State': 'Mid-American',
	'Toledo': 'Mid-American',
	'Western Michigan': 'Mid-American',
	'Central Michigan': 'Mid-American',
	'Eastern Michigan': 'Mid-American',
	'Northern Illinois': 'Mid-American',
	
	'Notre Dame': 'Independents',
	'BYU': 'Independents',
	'Liberty': 'Independents',
	'Army': 'Independents',
	'New Mexico State': 'Independents',
	'Connecticut': 'Independents',
	'Massachusetts': 'Independents',
}